FROM php:8.2-apache

RUN apt-get update && apt-get install -y msmtp ca-certificates && rm -rf /var/lib/apt/lists/*

RUN echo 'sendmail_path = "/usr/bin/msmtp -t --read-envelope-from"' \
    > /usr/local/etc/php/conf.d/mail.ini

COPY docker-helfende-entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
CMD ["apache2-foreground"]
