/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    'shop-items': ShopItem;
    bundles: Bundle;
    podcasts: Podcast;
    media: Media;
    'content-files': ContentFile;
    orders: Order;
    categories: Category;
    reviews: Review;
    discounts: Discount;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    'shop-items': ShopItemsSelect<false> | ShopItemsSelect<true>;
    bundles: BundlesSelect<false> | BundlesSelect<true>;
    podcasts: PodcastsSelect<false> | PodcastsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'content-files': ContentFilesSelect<false> | ContentFilesSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    discounts: DiscountsSelect<false> | DiscountsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  /**
   * Admin kann alles verwalten, Mitglied hat Zugang zum Mitgliederbereich
   */
  role?: ('admin' | 'member') | null;
  firstName?: string | null;
  lastName?: string | null;
  phone?: string | null;
  /**
   * Alle gekauften/gebuchten Shop-Items
   */
  purchasedItems?: (string | ShopItem)[] | null;
  purchasedBundles?: (string | Bundle)[] | null;
  /**
   * Aktive Einzeltrainings mit Ablaufdatum
   */
  trainingAccess?:
    | {
        training: string | ShopItem;
        startDate: string;
        endDate: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Alle Shop-Elemente: Veranstaltungen, Trainings, Videos, Audio, Bücher etc.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shop-items".
 */
export interface ShopItem {
  id: string;
  title: string;
  slug: string;
  itemType:
    | 'seminar'
    | 'workshop'
    | 'vortrag'
    | 'einzeltraining'
    | 'video'
    | 'audio'
    | 'begleitmaterial'
    | 'buch'
    | 'kunst';
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Wird in der Shop-Übersicht angezeigt (max. 300 Zeichen)
   */
  shortDescription?: string | null;
  image?: (string | null) | Media;
  /**
   * Optionale zusätzliche Bilder
   */
  gallery?:
    | {
        image: string | Media;
        id?: string | null;
      }[]
    | null;
  pricing: {
    price: number;
    /**
     * Durchgestrichener Originalpreis (optional)
     */
    comparePrice?: number | null;
    isFree?: boolean | null;
    /**
     * Erlaubt dem Kunden in Raten zu bezahlen
     */
    installmentEnabled?: boolean | null;
    /**
     * In wie vielen monatlichen Raten darf bezahlt werden? (2-12)
     */
    installmentCount?: number | null;
    /**
     * Wird automatisch berechnet wenn leer (Preis / Anzahl Raten)
     */
    installmentAmount?: number | null;
  };
  /**
   * Nur für Seminare, Workshops und Vorträge
   */
  eventDetails?: {
    date?: string | null;
    /**
     * Optional, für mehrtägige Events
     */
    endDate?: string | null;
    locationName?: string | null;
    locationAddress?: string | null;
    isOnline?: boolean | null;
    /**
     * Wird nur für gebuchte Teilnehmer sichtbar
     */
    onlineLink?: string | null;
    /**
     * Leer = unbegrenzt
     */
    maxParticipants?: number | null;
    currentParticipants?: number | null;
  };
  /**
   * Nur für Einzeltrainings
   */
  trainingDetails?: {
    /**
     * Wie lange hat der Käufer Zugang? (z.B. 4-8 Wochen)
     */
    durationWeeks?: number | null;
    modules?:
      | {
          title: string;
          description?: string | null;
          /**
           * In welcher Woche wird freigeschaltet?
           */
          weekNumber?: number | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Nur für Video-, Audio- und Begleitmaterial
   */
  digitalDetails?: {
    /**
     * z.B. MP4, MP3, PDF
     */
    format?: string | null;
    /**
     * z.B. "45 Min." oder "120 Seiten"
     */
    duration?: string | null;
    /**
     * Link zu einer kostenlosen Vorschau (optional)
     */
    previewUrl?: string | null;
    /**
     * Die eigentliche Video-/Audio-/PDF-Datei (nur für Käufer zugänglich)
     */
    contentFile?: (string | null) | ContentFile;
  };
  /**
   * Nur für Bücher
   */
  bookDetails?: {
    author?: string | null;
    isbn?: string | null;
    pages?: number | null;
    publisher?: string | null;
    /**
     * 0 = Kostenloser Versand
     */
    shippingCost?: number | null;
  };
  /**
   * Nur für Kunstwerke
   */
  kunstDetails?: {
    /**
     * z.B. Acryl auf Leinwand, Aquarell, Mischtechnik
     */
    medium?: string | null;
    /**
     * z.B. 60 x 80 cm
     */
    dimensions?: string | null;
    year?: number | null;
    /**
     * Kunstwerke sind standardmäßig Unikate (Stückzahl 1)
     */
    isUnikat?: boolean | null;
    /**
     * Optional: Link zu einem Video über das Kunstwerk oder den Entstehungsprozess
     */
    videoUrl?: string | null;
    /**
     * Optional: Video-Datei direkt hochladen
     */
    videoFile?: (string | null) | ContentFile;
    /**
     * 0 = Kostenloser Versand oder Abholung
     */
    shippingCost?: number | null;
  };
  /**
   * Nur für Events (Seminar, Workshop, Vortrag)
   */
  cancellation?: {
    /**
     * ⚠️ Beim Speichern werden alle Buchenden automatisch per E-Mail benachrichtigt
     */
    isCancelled?: boolean | null;
    cancellationReason?: string | null;
  };
  /**
   * z.B. Abhängigkeiten, Bewusstseinsarchitektur
   */
  categories?: (string | Category)[] | null;
  /**
   * Themenbundles, zu denen dieses Item gehört
   */
  bundles?: (string | Bundle)[] | null;
  status: 'draft' | 'published' | 'sold_out' | 'archived';
  /**
   * Wird auf der Startseite angezeigt
   */
  featured?: boolean | null;
  /**
   * Niedrigere Zahl = weiter oben
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Video-, Audio- und PDF-Dateien für digitale Produkte
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-files".
 */
export interface ContentFile {
  id: string;
  /**
   * Kurze Beschreibung der Datei
   */
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Themen-Kategorien zum Filtern (z.B. Abhängigkeiten, Bewusstseinsarchitektur)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  /**
   * z.B. Abhängigkeiten, Bewusstseinsarchitektur, Diskohärenzmodell
   */
  name: string;
  slug: string;
  description?: string | null;
  image?: (string | null) | Media;
  /**
   * Niedrigere Zahl = weiter oben
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Themenbundles: Gruppiere mehrere Shop-Items zu einem Bundle-Angebot
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bundles".
 */
export interface Bundle {
  id: string;
  /**
   * z.B. "Abhängigkeiten — Komplett-Paket"
   */
  name: string;
  slug: string;
  /**
   * Kann im Admin jederzeit um neue Themen erweitert werden
   */
  theme: 'abhaengigkeiten' | 'bewusstseinsarchitektur' | 'diskohaerenzmodell' | 'sonstiges';
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  shortDescription?: string | null;
  image?: (string | null) | Media;
  /**
   * Welche Shop-Items sind in diesem Bundle enthalten?
   */
  items: (string | ShopItem)[];
  /**
   * Reduzierter Gesamtpreis für das Bundle (günstiger als Einzelkauf)
   */
  bundlePrice: number;
  /**
   * z.B. "Du sparst 25%" — wird automatisch berechnet wenn leer
   */
  savingsText?: string | null;
  installmentEnabled?: boolean | null;
  installmentCount?: number | null;
  status: 'draft' | 'published' | 'archived';
  updatedAt: string;
  createdAt: string;
}
/**
 * Podcast-Episoden für die Landingpage
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "podcasts".
 */
export interface Podcast {
  id: string;
  title: string;
  slug: string;
  episodeNumber?: number | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  shortDescription?: string | null;
  coverImage?: (string | null) | Media;
  /**
   * Link zur Podcast-Datei (Spotify, Apple Podcasts, eigener Host etc.)
   */
  audioUrl?: string | null;
  spotifyUrl?: string | null;
  applePodcastsUrl?: string | null;
  /**
   * z.B. "45 Min."
   */
  duration?: string | null;
  publishDate?: string | null;
  /**
   * Shop-Items die zum Thema dieser Episode passen
   */
  relatedItems?: (string | ShopItem)[] | null;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * Alle Bestellungen und Buchungen
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: string;
  orderNumber: string;
  customer: string | User;
  items: {
    itemType: 'shop-item' | 'bundle';
    shopItem?: (string | null) | ShopItem;
    bundle?: (string | null) | Bundle;
    quantity: number;
    unitPrice: number;
    id?: string | null;
  }[];
  subtotal?: number | null;
  total: number;
  paymentType: 'full' | 'installment';
  installmentDetails?: {
    totalInstallments?: number | null;
    amountPerInstallment?: number | null;
    paidInstallments?: number | null;
    nextPaymentDate?: string | null;
  };
  status: 'pending' | 'paid' | 'installment_active' | 'cancelled' | 'refunded' | 'payment_failed';
  shippingAmount?: number | null;
  discountCode?: string | null;
  discountAmount?: number | null;
  stripeSessionId?: string | null;
  stripePaymentIntentId?: string | null;
  stripeSubscriptionId?: string | null;
  /**
   * Vom Kunden eingereichte Widerrufsanfrage
   */
  withdrawal?: {
    status?: ('none' | 'requested' | 'reviewed' | 'completed' | 'rejected') | null;
    requestedAt?: string | null;
    requestedByName?: string | null;
    requestedByEmail?: string | null;
  };
  /**
   * Nur fuer physische Produkte (Buecher etc.)
   */
  shippingAddress?: {
    street?: string | null;
    city?: string | null;
    zip?: string | null;
    country?: string | null;
  };
  /**
   * Nur fuer physische Produkte (Buecher, Kunst)
   */
  fulfillment?: {
    shippingStatus?: ('not_applicable' | 'pending' | 'shipped' | 'delivered') | null;
    /**
     * DHL, Hermes, etc.
     */
    trackingNumber?: string | null;
    shippedAt?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Kundenbewertungen — können von Besuchern ohne Login abgegeben werden
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: string;
  /**
   * Name des Bewerters
   */
  name: string;
  text: string;
  rating: number;
  /**
   * z.B. "Workshop-Teilnehmerin" — wird vom Besucher ausgefüllt
   */
  context?: string | null;
  /**
   * Nur freigegebene Bewertungen werden auf der Startseite angezeigt. Susanne kann hier Bewertungen ausblenden.
   */
  approved?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Rabattcodes und Gutscheine für den Shop
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discounts".
 */
export interface Discount {
  id: string;
  /**
   * z.B. SOMMER20 — wird automatisch großgeschrieben
   */
  code: string;
  type: 'percentage' | 'fixed';
  /**
   * Bei Prozent: 20 = 20%. Bei festem Betrag: 10 = 10€
   */
  value: number;
  maxUses?: number | null;
  usedCount?: number | null;
  /**
   * Leer lassen für unbegrenzte Gültigkeit
   */
  expiresAt?: string | null;
  active?: boolean | null;
  /**
   * Nur für dich sichtbar, z.B. "Weihnachtsaktion 2026"
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'shop-items';
        value: string | ShopItem;
      } | null)
    | ({
        relationTo: 'bundles';
        value: string | Bundle;
      } | null)
    | ({
        relationTo: 'podcasts';
        value: string | Podcast;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'content-files';
        value: string | ContentFile;
      } | null)
    | ({
        relationTo: 'orders';
        value: string | Order;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'reviews';
        value: string | Review;
      } | null)
    | ({
        relationTo: 'discounts';
        value: string | Discount;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  firstName?: T;
  lastName?: T;
  phone?: T;
  purchasedItems?: T;
  purchasedBundles?: T;
  trainingAccess?:
    | T
    | {
        training?: T;
        startDate?: T;
        endDate?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shop-items_select".
 */
export interface ShopItemsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  itemType?: T;
  description?: T;
  shortDescription?: T;
  image?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  pricing?:
    | T
    | {
        price?: T;
        comparePrice?: T;
        isFree?: T;
        installmentEnabled?: T;
        installmentCount?: T;
        installmentAmount?: T;
      };
  eventDetails?:
    | T
    | {
        date?: T;
        endDate?: T;
        locationName?: T;
        locationAddress?: T;
        isOnline?: T;
        onlineLink?: T;
        maxParticipants?: T;
        currentParticipants?: T;
      };
  trainingDetails?:
    | T
    | {
        durationWeeks?: T;
        modules?:
          | T
          | {
              title?: T;
              description?: T;
              weekNumber?: T;
              id?: T;
            };
      };
  digitalDetails?:
    | T
    | {
        format?: T;
        duration?: T;
        previewUrl?: T;
        contentFile?: T;
      };
  bookDetails?:
    | T
    | {
        author?: T;
        isbn?: T;
        pages?: T;
        publisher?: T;
        shippingCost?: T;
      };
  kunstDetails?:
    | T
    | {
        medium?: T;
        dimensions?: T;
        year?: T;
        isUnikat?: T;
        videoUrl?: T;
        videoFile?: T;
        shippingCost?: T;
      };
  cancellation?:
    | T
    | {
        isCancelled?: T;
        cancellationReason?: T;
      };
  categories?: T;
  bundles?: T;
  status?: T;
  featured?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bundles_select".
 */
export interface BundlesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  theme?: T;
  description?: T;
  shortDescription?: T;
  image?: T;
  items?: T;
  bundlePrice?: T;
  savingsText?: T;
  installmentEnabled?: T;
  installmentCount?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "podcasts_select".
 */
export interface PodcastsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  episodeNumber?: T;
  description?: T;
  shortDescription?: T;
  coverImage?: T;
  audioUrl?: T;
  spotifyUrl?: T;
  applePodcastsUrl?: T;
  duration?: T;
  publishDate?: T;
  relatedItems?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-files_select".
 */
export interface ContentFilesSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  customer?: T;
  items?:
    | T
    | {
        itemType?: T;
        shopItem?: T;
        bundle?: T;
        quantity?: T;
        unitPrice?: T;
        id?: T;
      };
  subtotal?: T;
  total?: T;
  paymentType?: T;
  installmentDetails?:
    | T
    | {
        totalInstallments?: T;
        amountPerInstallment?: T;
        paidInstallments?: T;
        nextPaymentDate?: T;
      };
  status?: T;
  shippingAmount?: T;
  discountCode?: T;
  discountAmount?: T;
  stripeSessionId?: T;
  stripePaymentIntentId?: T;
  stripeSubscriptionId?: T;
  withdrawal?:
    | T
    | {
        status?: T;
        requestedAt?: T;
        requestedByName?: T;
        requestedByEmail?: T;
      };
  shippingAddress?:
    | T
    | {
        street?: T;
        city?: T;
        zip?: T;
        country?: T;
      };
  fulfillment?:
    | T
    | {
        shippingStatus?: T;
        trackingNumber?: T;
        shippedAt?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  image?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  name?: T;
  text?: T;
  rating?: T;
  context?: T;
  approved?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discounts_select".
 */
export interface DiscountsSelect<T extends boolean = true> {
  code?: T;
  type?: T;
  value?: T;
  maxUses?: T;
  usedCount?: T;
  expiresAt?: T;
  active?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Einstellungen für die Startseite und allgemeine Seitenoptionen
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  /**
   * Das große Portraitbild auf der Startseite (wird im Kreis angezeigt)
   */
  heroImage?: (string | null) | Media;
  /**
   * Die große Überschrift auf der Startseite
   */
  heroTitle?: string | null;
  /**
   * Der Text unter der Überschrift auf der Startseite
   */
  heroSubtitle?: string | null;
  quoteText?: string | null;
  /**
   * Bewertungen und Erfahrungsberichte von Teilnehmern
   */
  testimonials?:
    | {
        /**
         * z.B. "Maria K." oder "Thomas"
         */
        name: string;
        text: string;
        rating?: number | null;
        /**
         * z.B. "Workshop-Teilnehmerin" oder "Einzeltraining"
         */
        context?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  heroImage?: T;
  heroTitle?: T;
  heroSubtitle?: T;
  quoteText?: T;
  testimonials?:
    | T
    | {
        name?: T;
        text?: T;
        rating?: T;
        context?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}